default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: 20
  encoding: utf8

development:
  <<: *default
  database: rspec_optimization_development

test:
  <<: *default
  database: rspec_optimization_test
